import type { Property, Settings, Testimonial } from "./types";
export const defaultSettings: Settings = {
  phone: "",
  whatsapp: "",
  email: "hello@drishyam.example",
  address: "Office address to be updated",
  hours: "Monday – Saturday · 10:00 AM – 7:00 PM (sample)",
  areas: ["Surat (sample service area)"],
  rentalEnabled: false,
  leadGating: false,
  demo: true,
};
const base = {
  description:
    "An illustrative property to preview the Drishyam Realty experience. Generous living spaces, thoughtful proportions, and a considered connection to the outdoors create room for everyday life. This is sample inventory; specifications and prices are for demonstration only.",
  furnishing: "Unfurnished",
  possession: "Ready to move",
  status: "Available",
  condition: "New",
  featured: true,
  amenities: [
    "Covered parking",
    "Landscaped gardens",
    "24-hour security",
    "Lift",
    "Power backup",
  ],
  createdAt: "2026-10-01T00:00:00.000Z",
  demo: true,
};
export const demoProperties: Property[] = [
  {
    ...base,
    id: "DR-DEMO-001",
    slug: "the-courtyard-residence",
    title: "The Courtyard Residence",
    category: "Residential",
    type: "Villa / Bungalow",
    location: "Vesu, Surat",
    price: 28500000,
    area: 3400,
    carpetArea: 2450,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 2,
    parking: 2,
    images: ["/images/hero.jpg", "/images/interior.jpg", "/images/villa.jpg"],
    floor: "Ground + 1",
    facing: "East",
    age: "New construction",
  },
  {
    ...base,
    id: "DR-DEMO-002",
    slug: "skyline-residences",
    title: "Skyline Residences",
    category: "Residential",
    type: "Apartment",
    location: "Pal, Surat",
    price: 12500000,
    area: 2150,
    carpetArea: 1550,
    bedrooms: 3,
    bathrooms: 3,
    images: ["/images/interior.jpg", "/images/hero.jpg"],
    floor: "8 of 14",
    facing: "North",
  },
  {
    ...base,
    id: "DR-DEMO-003",
    slug: "the-business-address",
    title: "The Business Address",
    category: "Commercial",
    type: "Office",
    location: "Piplod, Surat",
    price: 8900000,
    area: 1250,
    bedrooms: 0,
    bathrooms: 2,
    images: ["/images/office.jpg", "/images/interior.jpg"],
    furnishing: "Furnished",
    amenities: [
      "Covered parking",
      "24-hour security",
      "Lift",
      "Power backup",
      "Visitor lounge",
    ],
  },
  {
    ...base,
    id: "DR-DEMO-004",
    slug: "garden-view-apartment",
    title: "Garden View Apartment",
    category: "Residential",
    type: "Apartment",
    location: "Adajan, Surat",
    price: 7800000,
    area: 1650,
    bedrooms: 2,
    bathrooms: 2,
    images: ["/images/interior.jpg", "/images/villa.jpg"],
    condition: "Resale",
  },
  {
    ...base,
    id: "DR-DEMO-005",
    slug: "the-avenue-showroom",
    title: "The Avenue Showroom",
    category: "Commercial",
    type: "Shop / Showroom",
    location: "Vesu, Surat",
    price: 19000000,
    area: 1800,
    bedrooms: 0,
    bathrooms: 1,
    images: ["/images/office.jpg"],
    condition: "Resale",
  },
  {
    ...base,
    id: "DR-DEMO-006",
    slug: "a-place-to-build",
    title: "A Place to Build",
    category: "Land",
    type: "Land / Plot",
    location: "Pal, Surat",
    price: 22000000,
    area: 4000,
    plotArea: 4000,
    bedrooms: 0,
    bathrooms: 0,
    images: ["/images/villa.jpg"],
    amenities: ["Road access", "Water connection"],
    possession: "Immediate",
  },
];
export function formatPrice(n: number) {
  return n >= 10000000
    ? `₹${(n / 10000000).toFixed(2).replace(/0$/, "")} Cr`
    : `₹${(n / 100000).toFixed(0)} Lac`;
}

// Sample reviews so the testimonials layout can be previewed. They are hidden when DEMO_MODE=false. */
export const demoTestimonials: Testimonial[] = [
  {
    id: "demo-review-1",
    name: "Sample Client",
    type: "Buyers",
    quote:
      "They explained every step of the purchase and never rushed us into a decision.",
    location: "Vesu, Surat",
    rating: 5,
    demo: true,
  },
  {
    id: "demo-review-2",
    name: "Sample Client",
    type: "Sellers",
    quote:
      "Our shop was listed properly and we had genuine enquiries within the first few weeks.",
    location: "Adajan, Surat",
    rating: 5,
    demo: true,
  },
  {
    id: "demo-review-3",
    name: "Sample Client",
    type: "Investors",
    quote:
      "Honest advice on the budget. We ended up with a better plot than we had planned for.",
    location: "Pal, Surat",
    rating: 4,
    demo: true,
  },
  {
    id: "demo-review-4",
    name: "Sample Client",
    type: "Buyers",
    quote:
      "Clear communication from the first call to the final site visit. No surprises.",
    location: "Piplod, Surat",
    rating: 5,
    demo: true,
  },
  {
    id: "demo-review-5",
    name: "Sample Client",
    type: "Sellers",
    quote:
      "Helpful people who actually return calls. That alone made the whole sale easier.",
    location: "Althan, Surat",
    rating: 5,
    demo: true,
  },
  {
    id: "demo-review-6",
    name: "Sample Client",
    type: "Buyers",
    quote:
      "We found an office that suited the team and the price worked for us.",
    location: "Ring Road, Surat",
    rating: 4,
    demo: true,
  },
  {
    id: "demo-review-7",
    name: "Sample Client",
    type: "Investors",
    quote:
      "They shared the local market picture openly, including the downsides. I appreciated that.",
    location: "Dumas Road, Surat",
    rating: 5,
    demo: true,
  },
];
