export type Property = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  type: string;
  location: string;
  address?: string;
  price: number;
  area: number;
  carpetArea?: number;
  plotArea?: number;
  bedrooms: number;
  bathrooms: number;
  balconies?: number;
  parking?: number;
  furnishing: string;
  possession: string;
  status: string;
  condition: string;
  featured: boolean;
  images: string[];
  amenities: string[];
  landmarks?: string[];
  floor?: string;
  facing?: string;
  age?: string;
  createdAt: string;
  demo: boolean;
  showOnBuy?: boolean;
  showOnSell?: boolean;
  latitude?: number;
  longitude?: number;
  videoUrl?: string;
  documentation?: string;
};
export type Settings = {
  phone: string;
  whatsapp: string;
  email: string;
  address: string;
  hours: string;
  areas: string[];
  rentalEnabled: boolean;
  leadGating: boolean;
  demo: boolean;
};
export type Testimonial = {
  id: string;
  name: string;
  type: string;
  quote: string;
  location: string;
  rating?: number;
  image?: string;
  videoUrl?: string;
  demo?: boolean;
};
